Models/About.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace RocStudiosMVCProject.Models
{
    public class About
    {
        [Key]
        public int id { get; set; }
        [Required]
        [Display(Name = "About In English")]
        public string aboutEng { get; set; }
        [Required]
        [Display(Name = "About In Arabic")]
        public string aboutAr { get; set; }
        [Required]
        [Display(Name = "About Display Image")]
        public string aboutImg { get; set; }
        [Required]
        [Display(Name = "About Image Path")]
        public string ImgPath { get; set; }

    }
}

Controllers/AboutController.cs
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using RocStudiosMVCProject.Models;



namespace RocStudiosMVCProject.Controllers
{
    public class AboutController : Controller
    {
        // GET: About
        context ct = new context();

        public ActionResult Index()
        {
            var aboutData = ct.abouts.ToList();

            return View(aboutData);
        }
        [HttpGet]
        public ActionResult Edit(int id)
        {
            var aboutData = ct.abouts.Single(a => a.id == id);

            return View(aboutData);
        }
        [HttpPost]
        public ActionResult Edit(HttpPostedFileBase file,About about)
        {
            
            var aboutData = ct.abouts.Single(a => a.id == about.id );
            if (about.id == 0)
            {
                return HttpNotFound();
            }
            else
            {
                string imgName = Path.GetFileName(file.FileName);
                string imgext = Path.GetExtension(imgName);
                string imgPath = Path.Combine(Server.MapPath("~/public/Img/About"), imgName);
                string oldImgPath = Path.Combine(Server.MapPath("~/public/Img/About"), aboutData.aboutImg);
                FileInfo fi = new FileInfo(oldImgPath);
                if (fi != null)
                {
                   // System.IO.File.Delete(Server.MapPath(oldImgPath));
                    fi.Delete();
                }

                file.SaveAs(imgPath);

                aboutData.aboutEng = about.aboutEng;
                aboutData.aboutAr = about.aboutAr;
                aboutData.aboutImg = imgName;
                aboutData.ImgPath = imgPath;
            }
            ct.SaveChanges();
            return RedirectToAction("Index");
        }


    }
}

Views/About/Edit.cshtml
@model RocStudiosMVCProject.Models.About

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_DashBoardLayout.cshtml";
}


@using (Html.BeginForm("Edit", "About", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.id)
    <div class=" container pt-20">
        <div class="h-4/5 flex items-center justify-center bg-gray-50 py-12 px-4 sm:px-6 lg:px-8">
            <div class="max-w-md w-full space-y-8">

                <div>
                    <div class="form-group">
                        <label for="about" class="block">
                            @Html.LabelFor(model => model.aboutEng, htmlAttributes: new { @class = "control-label col-md-2" })
                        </label>
                        <div class="mt-1">
                            @Html.TextAreaFor(model => model.aboutEng, htmlAttributes: new { @class = "px-3 py-2 shadow-sm focus:outline-none focus:ring-secodary focus:border-secodary focus:z-10 mt-1 block w-full sm:text-sm border border-gray-300 rounded-md", @rows = "4" })
                        </div>
                        <p class="mt-2">
                            @Html.ValidationMessageFor(model => model.aboutEng, "", new { @class = "text-danger" })
                        </p>
                    </div>
                </div>
                <div>
                    <div class="form-group">
                        <label for="about" class="block">
                            @Html.LabelFor(model => model.aboutAr, htmlAttributes: new { @class = "control-label col-md-2" })
                        </label>
                        <div class="mt-1">
                            @Html.TextAreaFor(model => model.aboutAr, htmlAttributes: new { @class = "px-3 py-2 shadow-sm focus:outline-none focus:ring-secodary focus:border-secodary focus:z-10 mt-1 block w-full sm:text-sm border border-gray-300 rounded-md", @rows = "4" })
                        </div>
                        <p class="mt-2">
                            @Html.ValidationMessageFor(model => model.aboutAr, "", new { @class = "text-danger" })
                        </p>
                    </div>
                </div>
                <div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.aboutImg, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.TextBoxFor(model => model.aboutImg, htmlAttributes: new { @class = "px-3 py-2 shadow-sm focus:outline-none focus:ring-secodary focus:border-secodary focus:z-10 mt-1 block w-full sm:text-sm border border-gray-300 rounded-md", @disabled = "disabled" })
                            @Html.ValidationMessageFor(model => model.aboutImg, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>

                    <div class="mt-1 flex justify-center px-6 pt-5 pb-6 border-2 border-gray-300 border-dashed rounded-md">
                        <div class="space-y-1 text-center">
                            <svg class="mx-auto h-12 w-12 text-gray-400" stroke="currentColor" fill="none" viewBox="0 0 48 48" aria-hidden="true">
                                <path d="M28 8H12a4 4 0 00-4 4v20m32-12v8m0 0v8a4 4 0 01-4 4H12a4 4 0 01-4-4v-4m32-4l-3.172-3.172a4 4 0 00-5.656 0L28 28M8 32l9.172-9.172a4 4 0 015.656 0L28 28m0 0l4 4m4-24h8m-4-4v8m-12 4h.02" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />
                            </svg>
                            <div class="flex text-sm text-gray-600">
                                <label for="file-upload" class="relative cursor-pointer bg-white rounded-md font-medium text-secodary hover:text-secodary focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-secodary">
                                    <span><input name="file" type="file" class=""></span>

                                </label>
                            </div>
                            <p class="text-xs text-gray-500">
                                PNG, JPG, GIF up to 10MB
                            </p>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Save" class="group relative w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-primary hover:bg-secodary focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-secodary" />
                        </div>
                    </div>
                    <div class="hover:text-secodary">
                        @Html.ActionLink("Back to List", "Index")
                    </div>
                </div>
        </div>
    </div>

}

Views/About/Index.cshtml
@model IEnumerable<RocStudiosMVCProject.Models.About>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_DashBoardLayout.cshtml";
}


<div class="flex flex-col pt-20">
    <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
        <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
            <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
                <table class="min-w-full divide-y divide-gray-200 ">
                    <thead class="bg-gray-50">

                        <tr>
                            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                About Eng
                            </th>
                            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                About Arabic
                            </th>

                            <th scope="col" class="px-6 py-3 text-center text-xs font-medium text-gray-500 uppercase tracking-wider">
                                About Img
                            </th>
                            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                Action
                            </th>
                        </tr>
                    </thead>
                    <tbody class="bg-white divide-y divide-gray-200">
                        @foreach (var item in Model)
                        {
                            <tr>


                                <td class="">
                                    <div class="text-sm text-gray-900">@Html.DisplayFor(modelItem => item.aboutEng)</div>
                                </td>
                                <td class="px-6 py-4 whitespace-nowrap">
                                    <div class="text-sm text-gray-900"> @Html.DisplayFor(modelItem => item.aboutAr)</div>
                                </td>

                                <td class="px-6 py-4 whitespace-nowrap">
                                    <div class="flex items-start">
                                        <div class="flex-shrink-0 h-32 w-32">
                                            <img class="h-32 w-32 rounded-full" src="@Url.Content("~/public/Img/About/" + item.aboutImg)" alt="">
                                        </div>
                                    </div>
                                </td>
                                <td class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                    <div class="group relative w-12 flex items-end justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-primary hover:bg-secodary focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-secodary">@Html.ActionLink("Edit", "Edit", new { id = item.id }) </div>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>